### ISSUE TITLE
RuntimeError: input.size(-1) must be equal to input_size. Expected 460, got 400

### ISSUE THREAD

**Issue by siyuyuan** [federico-giannoni/pyramid-nested-ner#1]
Thank you for your share. When I use your code to train my dataset, this bug occurs. Can you help me?
```
==============================
Training epoch 1...
==============================
HBox(children=(FloatProgress(value=0.0, max=145.0), HTML(value='')))
Traceback (most recent call last):

  File "C:\Users\yuansiyu\Desktop\Nested NER\main.py", line 129, in <module>
    grad_clip=5.0

  File "C:\Users\yuansiyu\Desktop\Nested NER\pyramid_nested_ner\training\trainer.py", line 92, in train
    train_loss = self._training_epoch(train_set, grad_clip)

  File "C:\Users\yuansiyu\Desktop\Nested NER\pyramid_nested_ner\training\trainer.py", line 133, in _training_epoch
    logits, remedy = self.nnet(**batch)

  File "E:\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)

  File "C:\Users\yuansiyu\Desktop\Nested NER\pyramid_nested_ner\model.py", line 28, in forward
    x, mask = self.encoder(*args, **kwargs)

  File "E:\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)

  File "C:\Users\yuansiyu\Desktop\Nested NER\pyramid_nested_ner\modules\encoding\sentence_encoder.py", line 69, in forward
    x, _ = self.rnn(x, word_mask)

  File "E:\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)

  File "C:\Users\yuansiyu\Desktop\Nested NER\pyramid_nested_ner\modules\rnn.py", line 73, in forward
    x, self.hidden = self.rnn(x, self.hidden)

  File "E:\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)

  File "E:\anaconda3\lib\site-packages\torch\nn\modules\rnn.py", line 574, in forward
    self.check_forward_args(input, hx, batch_sizes)

  File "E:\anaconda3\lib\site-packages\torch\nn\modules\rnn.py", line 525, in check_forward_args
    self.check_input(input, batch_sizes)

  File "E:\anaconda3\lib\site-packages\torch\nn\modules\rnn.py", line 179, in check_input
    self.input_size, input.size(-1)))

RuntimeError: input.size(-1) must be equal to input_size. Expected 460, got 400
```

**Comment by federico-giannoni** [comment]
Hello! Are you running using the Python Notebook? Can you provide me a snippet of your data? It looks like there are shape issues when it's passed to the RNN.

**Comment by siyuyuan** [comment]
> Hello! Are you running using the Python Notebook? Can you provide me a snippet of your data? It looks like there are shape issues when it's passed to the RNN.

Thank you very much for your reply. I have handle the debug i mentioned above, but there is a new bug
```
==============================
Training epoch 1...
==============================
  0%|                                                  | 0/1156 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/dl/zwq/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-aa03156a2925>", line 1, in <module>
    runfile('/home/dl/yuansiyu/pyramid/main.py', wdir='/home/dl/yuansiyu/pyramid')
  File "/home/dl/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/dl/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/dl/yuansiyu/pyramid/main.py", line 129, in <module>
    grad_clip=5.0
  File "/home/dl/yuansiyu/pyramid/pyramid_nested_ner/training/trainer.py", line 92, in train
    train_loss = self._training_epoch(train_set, grad_clip)
  File "/home/dl/yuansiyu/pyramid/pyramid_nested_ner/training/trainer.py", line 139, in _training_epoch
    loss = self.compute_loss(logits, y, batch['word_mask'], remedy, remedy_y)
  File "/home/dl/yuansiyu/pyramid/pyramid_nested_ner/training/trainer.py", line 196, in compute_loss
    ml_loss = nn.BCEWithLogitsLoss(reduction='none')(remedy_logits, remedy_y)
  File "/home/dl/zwq/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dl/zwq/anaconda3/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 632, in forward
    reduction=self.reduction)
  File "/home/dl/zwq/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 2580, in binary_cross_entropy_with_logits
    raise ValueError("Target size ({}) must be the same as input size ({})".format(target.size(), input.size()))
ValueError: Target size (torch.Size([8, 223, 2])) must be the same as input size (torch.Size([8, 223, 4960]))
```
I try to debug and find that the remedy_y is not equal to B x S x 2 * C (in my code C = 2480). I do not know why the shape of remedy_y is B x S x 2 but not B x S x 2 * C

**Comment by federico-giannoni** [comment]
Thank you for the details. It appears there is a bug somewhere in the label encoding part, as the shape of the remedy solution should indeed be B x S x 2C (where the `2` represents the `I-` and the `B-` span annotation of IOB2). 

It would help me a lot if you could tell me if you are running the Notebook `test/Pyramid Nested NER - Custom Training.ipynb`. Additionally, a snippet of your data after it has been transformed in [legacy json RASA format](https://legacy-docs-v1.rasa.com/nlu/training-data-format/#json-format) would also help. In theory, the code should automatically encode labels starting from this format, so it could be that there are some errors in the spans that are defined in the json data file :)

**Comment by siyuyuan** [comment]
> Thank you for the details. It appears there is a bug somewhere in the label encoding part, as the shape of the remedy solution should indeed be B x S x 2C (where the `2` represents the `I-` and the `B-` span annotation of IOB2).
> 
> It would help me a lot if you could tell me if you are running the Notebook `test/Pyramid Nested NER - Custom Training.ipynb`. Additionally, a snippet of your data after it has been transformed in [legacy json RASA format](https://legacy-docs-v1.rasa.com/nlu/training-data-format/#json-format) would also help. In theory, the code should automatically encode labels starting from this format, so it could be that there are some errors in the spans that are defined in the json data file :)

I am running the Notebook and my dateset is same as you mentioned
```
{
  "text": "hexamethylphosphoramide, often abbreviated hmpa, is a phosphoramide an amide of phosphoric acid with the formula [ch32n]3po. this colorless liquid is a useful reagent in organic synthesis.",
  "entities": [
    {
      "name": "concept",
      "value": "amide",
      "start": 18,
      "stop": 23
    }
  ]
}
```
I am not sure what C is mean, it means the number of unique "value"  or it means the number of unique "name"

**Comment by siyuyuan** [comment]
> Thank you for the details. It appears there is a bug somewhere in the label encoding part, as the shape of the remedy solution should indeed be B x S x 2C (where the `2` represents the `I-` and the `B-` span annotation of IOB2).
> 
> It would help me a lot if you could tell me if you are running the Notebook `test/Pyramid Nested NER - Custom Training.ipynb`. Additionally, a snippet of your data after it has been transformed in [legacy json RASA format](https://legacy-docs-v1.rasa.com/nlu/training-data-format/#json-format) would also help. In theory, the code should automatically encode labels starting from this format, so it could be that there are some errors in the spans that are defined in the json data file :)

And when i check the code for PyramidLabelEncoder(), i find that for the code in pyramid_nested_ner/data/model.py in line 78
```
  self.label_encoder.fit(entities_lexicon)
```
but for the code in pyramid_nested_ner/data/dataset.py in line 83
```
self.label_encoder.fit([e.name for x in self.data for e in x.entities])
```
i want to know that what entities_lexicon looks like, it is value or it is name

**Comment by federico-giannoni** [comment]
The entities lexicon is just a list of entity names (in your case, the entity name would be `concept`). The problem I see with your data is that the entities do not match with tokens. For example, you have:

```
{
  "text": "hexamethylphosphoramide, often abbreviated hmpa, is a phosphoramide an amide of phosphoric acid with the formula [ch32n]3po. this colorless liquid is a useful reagent in organic synthesis.",
  "entities": [
    {
      "name": "concept",
      "value": "amide",
      "start": 18,
      "stop": 23
    }
  ]
}
```

Here, your tokens would be (assuming a whitespace tokeniser, which is the default): `['hexamethylphosphoramide,', 'often', 'abbreviated', 'hmpa'...]`. Your entity however (`amide`), is a substring of the first token... That is impossible to model since we are performing sequence labelling, therefore we can only assign a label to a full element of a sequence, not to a sub-string of it.

**Comment by siyuyuan** [comment]
> The entities lexicon is just a list of entity names (in your case, the entity name would be `concept`). The problem I see with your data is that the entities do not match with tokens. For example, you have:
> 
> ```
> {
>   "text": "hexamethylphosphoramide, often abbreviated hmpa, is a phosphoramide an amide of phosphoric acid with the formula [ch32n]3po. this colorless liquid is a useful reagent in organic synthesis.",
>   "entities": [
>     {
>       "name": "concept",
>       "value": "amide",
>       "start": 18,
>       "stop": 23
>     }
>   ]
> }
> ```
> 
> Here, your tokens would be (assuming a whitespace tokeniser, which is the default): `['hexamethylphosphoramide,', 'often', 'abbreviated', 'hmpa'...]`. Your entity however (`amide`), is a substring of the first token... That is impossible to model since we are performing sequence labelling, therefore we can only assign a label to a full element of a sequence, not to a sub-string of it.

Thank you so much for your reply.  Could you help me check the data format amended
```
{
  "text": "california is a state in the pacific region of the united states of america. with 39.5 million residents across a total area of about 163,696 square miles 423,970 km2, california is the most populous u.s. state and the third-largest by area, and is also the world's thirty-fourth most populous subnational entity. california is also the most populated subnational entity in north america, and has its state capital in sacramento. the greater los angeles area and the san francisco bay area are the nation's second- and fifth-most populous urban regions, with 18.7 million and 9.7 million residents respectively. los angeles is california's most populous city, and the country's second-most populous, after new york city. california also has the nation's most populous county, los angeles county, and its largest county by area, san bernardino county. the city and county of san francisco is both the country's second most densely populated major city after new york city and the fifth most densely populated county, behind only four of the five new york city boroughs.",
  "entities": [
    {
      "name": "concept",
      "value": "area",
      "start": 120,
      "stop": 124
    }
  ]
}
```
I still have some question.
1. In other words, entities lexicon is the entity's type(such as location, person and so on) and value is the entity's name?
2. Can i use the code to train the Chinese dataset?

**Comment by federico-giannoni** [comment]
The entities lexicon is your label space, therefore the list of entity names (as you said, `location`, `person`, `organisation`, etc. or any other label that you might have in your dataset). The value is the value for that entity as it appears in the text.

Assuming your dataset only has two examples, like:

```json
[
  {
    "text": "I need to book a flight to San Francisco .",
    "entities": [
      {
        "name": "city",
        "value": "San Francisco",
        "start": 27,
        "stop": 40
      }
    ]
  },
  {
    "text": "Joe Biden is the new president of the United States .",
    "entities": [
      {
        "name": "person",
        "value": "Joe Biden",
        "start": 0,
        "stop": 9
      },
     {
        "name": "country",
        "value": "United States",
        "start": 38,
        "stop": 51
      }
    ]
  },
```

Your entity-value pairs are:
1. `city=San Francisco` (`city` is the entity name and `San Francisco` the value);
2. `person=Joe Biden` (`person is the entity name and `Joe Biden` the value);
3. `country=United States` (`country` is the entity name and `United States` the value).

and your entity lexicon would contain `[None, 'city', 'person', 'country']` (the first `None` is for no-entity).

You can use the code to run on a Chinese dataset but I'm not sure if the whitespace tokeniser is good for Chinese. You can try and then eventually implement your own. For word embeddings, I don't know if [flair](https://github.com/flairNLP/flair) has anything that you can use out-of-the-box. If they don't, you are going to have to specify a custom torch embedding layer when you initialise the PyramidNer model (instead of passing `word_embeddings=['en-glove', 'en-crawl']`).

**Comment by siyuyuan** [comment]
> The entities lexicon is your label space, therefore the list of entity names (as you said, `location`, `person`, `organisation`, etc. or any other label that you might have in your dataset). The value is the value for that entity as it appears in the text.
> 
> Assuming your dataset only has two examples, like:
> 
> ```json
> [
>   {
>     "text": "I need to book a flight to San Francisco .",
>     "entities": [
>       {
>         "name": "city",
>         "value": "San Francisco",
>         "start": 27,
>         "stop": 40
>       }
>     ]
>   },
>   {
>     "text": "Joe Biden is the new president of the United States .",
>     "entities": [
>       {
>         "name": "person",
>         "value": "Joe Biden",
>         "start": 0,
>         "stop": 9
>       },
>      {
>         "name": "country",
>         "value": "United States",
>         "start": 38,
>         "stop": 51
>       }
>     ]
>   },
> ```
> 
> Your entity-value pairs are:
> 
> 1. `city=San Francisco` (`city` is the entity name and `San Francisco` the value);
> 2. `person=Joe Biden` (`person is the entity name and `Joe Biden` the value);
> 3. `country=United States` (`country` is the entity name and `United States` the value).
> 
> and your entity lexicon would contain `[None, 'city', 'person', 'country']` (the first `None` is for no-entity).
> 
> You can use the code to run on a Chinese dataset but I'm not sure if the whitespace tokeniser is good for Chinese. You can try and then eventually implement your own. For word embeddings, I don't know if [flair](https://github.com/flairNLP/flair) has anything that you can use out-of-the-box. If they don't, you are going to have to specify a custom torch embedding layer when you initialise the PyramidNer model (instead of passing `word_embeddings=['en-glove', 'en-crawl']`).

Thank you sooooo much!!!

**Comment by federico-giannoni** [comment]
You are welcome :) I will close this issue. If you have more questions reach out to me via email (you can find the address in my GitHub profile).
