### ISSUE TITLE
token_lexicon = {token for x in self.data for token in self.tokenizer(x)}

### ISSUE THREAD

**Issue by siyuyuan** [federico-giannoni/pyramid-nested-ner#2]
Sorry to bother you again. I still have some question.

In the data/dataset.py line 67-68

```

token_lexicon = {token for x in self.data for token in self.tokenizer(x)}

```

I think self.tokenizer(x) should be replace by self.tokenizer(x.text) since default_tokenizer is text.split() in util/text.py

**Comment by federico-giannoni** [comment]
Hello again! It seems you are right :) thanks for reporting this, I will
fix it as soon as I have the time.

**Comment by federico-giannoni** [comment]
fixed! (a bit late, sorry 😄)
